version: 2

models:
  - name: stg_players
    columns:
      - name: player_id
        tests:
          - not_null
          - unique
      - name: full_name
        tests:
          - not_null

  - name: stg_pitcher_game_logs
    columns:
      - name: player_id
        tests:
          - not_null
      - name: game_pk
        tests:
          - not_null
      - name: game_date
        tests:
          - not_null
