version: 2

models:
  - name: dim_pitcher
    columns:
      - name: player_id
        tests:
          - not_null
          - unique
      - name: full_name
        tests:
          - not_null

  - name: fact_pitcher_game
    columns:
      - name: player_id
        tests:
          - not_null
      - name: game_pk
        tests:
          - not_null
      - name: game_date
        tests:
          - not_null

  - name: mart_pitcher_season
    columns:
      - name: player_id
        tests:
          - not_null
          - unique
      - name: full_name
        tests:
          - not_null

  - name: dim_game
    columns:
      - name: game_pk
        tests:
          - not_null
          - unique
      - name: game_date
        tests:
          - not_null

  - name: mart_pitcher_rolling
    columns:
      - name: player_id
        tests:
          - not_null
      - name: game_pk
        tests:
          - not_null
      - name: game_date
        tests:
          - not_null
